### ISSUE TITLE
Unrecognized `--run_pipeline`   flag 

### ISSUE THREAD

**Issue by LeonardAukea** [kubeflow-kale/jupyterlab-kubeflow-kale#1]
I tried your titanic example using `COMPILE UPLOAD AND RUN`

```
Deployment Result
usage: kale [-h] --nb NB [--experiment_name EXPERIMENT_NAME]
[--pipeline_name PIPELINE_NAME]
[--pipeline_description PIPELINE_DESCRIPTION]
[--docker_image DOCKER_IMAGE] [--volumes [VOLUMES [VOLUMES ...]]]
[--deploy] [--kfp_dns KFP_DNS] [--jupyter_args JUPYTER_ARGS]
kale: error: unrecognized arguments: --run_pipeline
```

Using `COMPILE TO DSL`

```
Deployment Result
Traceback (most recent call last):
File "/opt/conda/bin/kale", line 10, in <module>
sys.exit(main())
File "/opt/conda/lib/python3.7/site-packages/kale/command_line.py", line 87, in main
auto_deploy=metadata_arguments['deploy'],
KeyError: 'deploy'
```

And `COMPILE AND UPLOAD`

```
usage: kale [-h] --nb NB [--experiment_name EXPERIMENT_NAME]
[--pipeline_name PIPELINE_NAME]
[--pipeline_description PIPELINE_DESCRIPTION]
[--docker_image DOCKER_IMAGE] [--volumes [VOLUMES [VOLUMES ...]]]
[--deploy] [--kfp_dns KFP_DNS] [--jupyter_args JUPYTER_ARGS]
kale: error: unrecognized arguments: --upload_pipeline
```

It seems like it's referencing non-existing flags

**Comment by StefanoFioravanzo** [comment]
Hello @LeonardAukea 

I have introduced these changes just a couple of days ago and had to fix a few bugs so it might be possible that you installed Kale in the middle of my fixing. Sorry about that.

You should be good to go with the current versions in `master`. Can you please try to reinstall both the python package and the jupyter extension from scratch?

**Comment by LeonardAukea** [comment]
Will do.

**Comment by LeonardAukea** [comment]
Ok, now it gives this. Using  the numpy example (transpose & matmul) 

```
10-09 18:36 | kubeflow-kale | INFO: Pipeline code saved at kfp_numpy-kale.kfp.py
10-09 18:36 | kubeflow-kale | ERROR: invalid syntax (pipeline_code.py, line 6)
10-09 18:36 | kubeflow-kale | ERROR: To see full traceback run Kale with --debug flag or have a look at kale.log logfile
```

log: 
```
10-09 18:35 | kubeflow-kale |  DEBUG: ------------- Kale Start Run -------------
10-09 18:35 | kubeflow-kale |  INFO: Pipeline code saved at kfp_numpy-kale.kfp.py
10-09 18:35 | kubeflow-kale |  DEBUG: invalid syntax (pipeline_code.py, line 6)
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/kale/core.py", line 117, in run
    return self.deploy_pipeline_to_kfp(self.output_path)
  File "/opt/conda/lib/python3.7/site-packages/kale/core.py", line 140, in deploy_pipeline_to_kfp
    spec.loader.exec_module(foo)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/tmppfdssyik/pipeline_code.py", line 6
    def create-matrices() -> str:
              ^
SyntaxError: invalid syntax
10-09 18:35 | kubeflow-kale |  ERROR: invalid syntax (pipeline_code.py, line 6)
10-09 18:35 | kubeflow-kale |  ERROR: To see full traceback run Kale with --debug flag or have a look at kale.log logfile
10-09 18:36 | kubeflow-kale |  DEBUG: ------------- Kale Start Run -------------
10-09 18:36 | kubeflow-kale |  INFO: Pipeline code saved at kfp_numpy-kale.kfp.py
10-09 18:36 | kubeflow-kale |  DEBUG: invalid syntax (pipeline_code.py, line 6)
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/kale/core.py", line 117, in run
    return self.deploy_pipeline_to_kfp(self.output_path)
  File "/opt/conda/lib/python3.7/site-packages/kale/core.py", line 140, in deploy_pipeline_to_kfp
    spec.loader.exec_module(foo)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/tmpn7s3mt4z/pipeline_code.py", line 6
    def create-matrices() -> str:
              ^
SyntaxError: invalid syntax
10-09 18:36 | kubeflow-kale |  ERROR: invalid syntax (pipeline_code.py, line 6)
10-09 18:36 | kubeflow-kale |  ERROR: To see full traceback run Kale with --debug flag or have a look at kale.log logfile
10-09 18:36 | kubeflow-kale |  DEBUG: ------------- Kale Start Run -------------
10-09 18:36 | kubeflow-kale |  INFO: Pipeline code saved at kfp_numpy-kale.kfp.py
10-09 18:36 | kubeflow-kale |  DEBUG: invalid syntax (pipeline_code.py, line 6)
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/kale/core.py", line 117, in run
    return self.deploy_pipeline_to_kfp(self.output_path)
  File "/opt/conda/lib/python3.7/site-packages/kale/core.py", line 140, in deploy_pipeline_to_kfp
    spec.loader.exec_module(foo)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/tmp_4gbrewh/pipeline_code.py", line 6
    def create-matrices() -> str:
              ^
SyntaxError: invalid syntax
10-09 18:36 | kubeflow-kale |  ERROR: invalid syntax (pipeline_code.py, line 6)
10-09 18:36 | kubeflow-kale |  ERROR: To see full traceback run Kale with --debug flag or have a look at kale.log logfile
```
The issue here is how you infer  the name of the function from the names provided by the tags. 

Do you need/want any help with this project (kale) btw?
